//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WENCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dk_rol_users
    {
        public string id { get; set; }
        public string user_id { get; set; }
        public int rol_id { get; set; }
        public string cod_empresa { get; set; }
    
        public virtual dk_roles dk_roles { get; set; }
        public virtual dk_users dk_users { get; set; }
    }
}
