//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WENCO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDWENCOEntities2 : DbContext
    {
        public BDWENCOEntities2()
            : base("name=BDWENCOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dk_rol_users> dk_rol_users { get; set; }
        public virtual DbSet<dk_roles> dk_roles { get; set; }
        public virtual DbSet<dk_users> dk_users { get; set; }
    }
}
